//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationVersion
    {
        public ApplicationVersion()
        {
            this.AssemblyApplicationVersions = new HashSet<AssemblyApplicationVersion>();
            this.GlobalSettings = new HashSet<GlobalSetting>();
            this.Hosts = new HashSet<Host>();
        }
    
        public long Id { get; set; }
        public System.DateTime CreateDttm { get; set; }
        public string Description { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<System.DateTime> EffectiveDttm { get; set; }
    
        public virtual ICollection<AssemblyApplicationVersion> AssemblyApplicationVersions { get; set; }
        public virtual ICollection<GlobalSetting> GlobalSettings { get; set; }
        public virtual ICollection<Host> Hosts { get; set; }
    }
}
