//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyVersion
    {
        public AssemblyVersion()
        {
            this.AssemblyApplicationVersions = new HashSet<AssemblyApplicationVersion>();
        }
    
        public long Id { get; set; }
        public string AssemblyName { get; set; }
        public string AssemblyDotNetVersion { get; set; }
        public System.DateTime LoadDttm { get; set; }
        public byte[] Executable { get; set; }
        public byte[] DebuggingSymbols { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual ICollection<AssemblyApplicationVersion> AssemblyApplicationVersions { get; set; }
    }
}
