//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyApplicationVersion
    {
        public string AssemblyName { get; set; }
        public string AssemblyDotNetVersion { get; set; }
        public long ApplicationVersionId { get; set; }
        public long AssemblyVersionId { get; set; }
    
        public virtual ApplicationVersion ApplicationVersion { get; set; }
        public virtual Assembly Assembly { get; set; }
        public virtual AssemblyVersion AssemblyVersion { get; set; }
    }
}
