//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InformagatorEntities : DbContext
    {
        public InformagatorEntities()
            : base("name=InformagatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Host> Hosts { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<StageParameter> StageParameters { get; set; }
        public virtual DbSet<Thread> Threads { get; set; }
    }
}
