//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public Host()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
