//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.StageParameters = new HashSet<StageParameter>();
        }
    
        public string Name { get; set; }
        public string ThreadName { get; set; }
        public int Sequence { get; set; }
        public bool IsEnabled { get; set; }
        public string StageAssembly { get; set; }
        public string StageType { get; set; }
        public string ErrorHandlerAssembly { get; set; }
        public string ErrorHandlerType { get; set; }
    
        public virtual Thread Thread { get; set; }
        public virtual ICollection<StageParameter> StageParameters { get; set; }
    }
}
