//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Stages = new HashSet<Stage>();
        }
    
        public long Id { get; set; }
        public long HostId { get; set; }
        public string Name { get; set; }
        public string WorkerAssemblyName { get; set; }
        public string WorkerAssemblyDotNetVersion { get; set; }
        public string WorkerType { get; set; }
        public bool AutoStart { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Host Host { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
    }
}
