//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackedMessage
    {
        public TrackedMessage()
        {
            this.TrackedMessageAttributes = new HashSet<TrackedMessageAttribute>();
        }
    
        public long Id { get; set; }
        public System.DateTime TrackDateTime { get; set; }
        public long MessageId { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.Guid> ProcessingSequenceId { get; set; }
        public Nullable<int> StageSequence { get; set; }
        public Nullable<int> MessageSequence { get; set; }
        public string StageName { get; set; }
        public string Exception { get; set; }
    
        public virtual ICollection<TrackedMessageAttribute> TrackedMessageAttributes { get; set; }
    }
}
