//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        public Assembly()
        {
            this.AssemblySystemConfigurations = new HashSet<AssemblySystemConfiguration>();
            this.AssemblyVersions = new HashSet<AssemblyVersion>();
            this.Stages = new HashSet<Stage>();
            this.Stages1 = new HashSet<Stage>();
            this.Workers = new HashSet<Worker>();
        }
    
        public string Name { get; set; }
        public string DotNetVersion { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AssemblySystemConfiguration> AssemblySystemConfigurations { get; set; }
        public virtual ICollection<AssemblyVersion> AssemblyVersions { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<Stage> Stages1 { get; set; }
        public virtual ICollection<Worker> Workers { get; set; }
    }
}
