//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.ProdProviders.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyVersion
    {
        public AssemblyVersion()
        {
            this.AssemblySystemConfigurations = new HashSet<AssemblySystemConfiguration>();
            this.StagesUsingErrorHandlers = new HashSet<Stage>();
            this.StagesUsingStages = new HashSet<Stage>();
            this.Workers = new HashSet<Worker>();
        }
    
        public long Id { get; set; }
        public string AssemblyName { get; set; }
        public string AssemblyDotNetVersion { get; set; }
        public System.DateTime LoadDttm { get; set; }
        public byte[] Executable { get; set; }
        public byte[] DebuggingSymbols { get; set; }
    
        public virtual ICollection<AssemblySystemConfiguration> AssemblySystemConfigurations { get; set; }
        public virtual ICollection<Stage> StagesUsingErrorHandlers { get; set; }
        public virtual ICollection<Stage> StagesUsingStages { get; set; }
        public virtual ICollection<Worker> Workers { get; set; }
    }
}
