//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.StageParameters = new HashSet<StageParameter>();
        }
    
        public long Id { get; set; }
        public long ThreadId { get; set; }
        public string Name { get; set; }
        public int Sequence { get; set; }
        public string StageAssemblyName { get; set; }
        public string StageAssemblyDotNetVersion { get; set; }
        public string StageType { get; set; }
        public string ErrorHandlerAssemblyName { get; set; }
        public string ErrorHandlerAssemblyDotNetVersion { get; set; }
        public string ErrorHandlerType { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Assembly Assembly1 { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<StageParameter> StageParameters { get; set; }
    }
}
