//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.ErrorHandlerParameters = new HashSet<ErrorHandlerParameter>();
            this.StageParameters = new HashSet<StageParameter>();
        }
    
        public long Id { get; set; }
        public long WorkerId { get; set; }
        public string Name { get; set; }
        public int Sequence { get; set; }
        public long StageAssemblyVersionId { get; set; }
        public string StageType { get; set; }
        public long ErrorHandlerAssemblyVersionId { get; set; }
        public string ErrorHandlerType { get; set; }
    
        public virtual AssemblyVersion ErrorHandlerAssemblyVersion { get; set; }
        public virtual AssemblyVersion StageAssemblyVersion { get; set; }
        public virtual ICollection<ErrorHandlerParameter> ErrorHandlerParameters { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<StageParameter> StageParameters { get; set; }
    }
}
