//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acadian.Informagator.ProdProviders.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfiguration
    {
        public SystemConfiguration()
        {
            this.AssemblySystemConfigurations = new HashSet<AssemblySystemConfiguration>();
            this.GlobalSettings = new HashSet<GlobalSetting>();
            this.Machines = new HashSet<Machine>();
        }
    
        public long Id { get; set; }
        public System.DateTime CreateDttm { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDttm { get; set; }
    
        public virtual ICollection<AssemblySystemConfiguration> AssemblySystemConfigurations { get; set; }
        public virtual ICollection<GlobalSetting> GlobalSettings { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
    }
}
