//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        public Assembly()
        {
            this.ErrorHandlers = new HashSet<ErrorHandler>();
            this.Stages = new HashSet<Stage>();
            this.Workers = new HashSet<Worker>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public long SystemConfigurationId { get; set; }
        public System.DateTime LoadDttm { get; set; }
        public byte[] Executable { get; set; }
        public byte[] DebuggingSymbols { get; set; }
    
        public virtual SystemConfiguration SystemConfiguration { get; set; }
        public virtual ICollection<ErrorHandler> ErrorHandlers { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<Worker> Workers { get; set; }
    }
}
