//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfigurationEntities : DbContext
    {
        public ConfigurationEntities()
            : base("name=ConfigurationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assembly> Assemblies { get; set; }
        public virtual DbSet<ErrorHandler> ErrorHandlers { get; set; }
        public virtual DbSet<ErrorHandlerParameter> ErrorHandlerParameters { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<MachineErrorHandler> MachineErrorHandlers { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<StageErrorHandler> StageErrorHandlers { get; set; }
        public virtual DbSet<StageParameter> StageParameters { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WorkerErrorHandler> WorkerErrorHandlers { get; set; }
        public virtual DbSet<WorkerParameter> WorkerParameters { get; set; }
    }
}
