//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorHandler
    {
        public ErrorHandler()
        {
            this.ErrorHandlerParameters = new HashSet<ErrorHandlerParameter>();
            this.MachineErrorHandlers = new HashSet<MachineErrorHandler>();
            this.StageErrorHandlers = new HashSet<StageErrorHandler>();
            this.WorkerErrorHandlers = new HashSet<WorkerErrorHandler>();
            this.SystemConfigurationErrorHandlers = new HashSet<SystemConfigurationErrorHandler>();
        }
    
        public long Id { get; set; }
        public long SystemConfigurationId { get; set; }
        public string Name { get; set; }
        public long AssemblyId { get; set; }
        public string Type { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual SystemConfiguration SystemConfiguration { get; set; }
        public virtual ICollection<ErrorHandlerParameter> ErrorHandlerParameters { get; set; }
        public virtual ICollection<MachineErrorHandler> MachineErrorHandlers { get; set; }
        public virtual ICollection<StageErrorHandler> StageErrorHandlers { get; set; }
        public virtual ICollection<WorkerErrorHandler> WorkerErrorHandlers { get; set; }
        public virtual ICollection<SystemConfigurationErrorHandler> SystemConfigurationErrorHandlers { get; set; }
    }
}
