//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.StageErrorHandlers = new HashSet<StageErrorHandler>();
            this.StageParameters = new HashSet<StageParameter>();
        }
    
        public long Id { get; set; }
        public long WorkerId { get; set; }
        public string Name { get; set; }
        public int Sequence { get; set; }
        public long AssemblyId { get; set; }
        public string Type { get; set; }
        public bool SuppressParentErrorHandlers { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<StageErrorHandler> StageErrorHandlers { get; set; }
        public virtual ICollection<StageParameter> StageParameters { get; set; }
    }
}
