//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfiguration
    {
        public SystemConfiguration()
        {
            this.Assemblies = new HashSet<Assembly>();
            this.ErrorHandlers = new HashSet<ErrorHandler>();
            this.Machines = new HashSet<Machine>();
        }
    
        public long Id { get; set; }
        public System.DateTime CreateDttm { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EffectiveDttm { get; set; }
        public int DefaultAdminServicePort { get; set; }
        public int DefaultInfoServicePort { get; set; }
    
        public virtual ICollection<Assembly> Assemblies { get; set; }
        public virtual ICollection<ErrorHandler> ErrorHandlers { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
    }
}
