//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerParameter
    {
        public long Id { get; set; }
        public long WorkerId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
