//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Stages = new HashSet<Stage>();
            this.WorkerErrorHandlers = new HashSet<WorkerErrorHandler>();
            this.WorkerParameters = new HashSet<WorkerParameter>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long MachineId { get; set; }
        public long AssemblyId { get; set; }
        public string Type { get; set; }
        public bool AutoStart { get; set; }
        public bool SuppressParentErrorHandlers { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<WorkerErrorHandler> WorkerErrorHandlers { get; set; }
        public virtual ICollection<WorkerParameter> WorkerParameters { get; set; }
    }
}
