//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Message
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAttribute
    {
        public long MessageId { get; set; }
        public string Attribute { get; set; }
        public string Value { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
