//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informagator.DBEntities.Message
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageAttributes = new HashSet<MessageAttribute>();
        }
    
        public long Id { get; set; }
        public string QueueName { get; set; }
        public System.DateTime AddDttm { get; set; }
        public Nullable<System.DateTime> DequeueDttm { get; set; }
        public string Body { get; set; }
        public System.Guid MessageId { get; set; }
    
        public virtual ICollection<MessageAttribute> MessageAttributes { get; set; }
    }
}
